### PR TITLE
Fix index error message

### LINKED ISSUE #214: [PE-D][Tester B] Incorrect error message. Should display an incorrect index error.
Steps to reproduce:

Run `addcc pi/1 ci/0`

Issue:

User may be confused as the input format is correct, just the value itself is incorrect.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: IzN432/ped#14

### LINKED ISSUE #233: [PE-D][Tester A] ConcertPhonebook: Index Error not specific enough
When running commands that involve indexes, any number above the Integer max number will show an invalid format error instead of an invalid index. However, this is inconsistent as compared to phone numbers which allow numbers larger than Integer max number.

Steps to reproduce:
1. Launch the application
2. Use any command that require an index in the field, such as `editp 834758725249805 n/abc`

Possible Fixes:
- Perhaps you can change the error to reflex invalid index instead?

Expected:
- An error to not show invalid format as the format is correct.

Actual:

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: InfinityTwo/ped#14

### PR DESCRIPTION
**Pull request by wes-w-z-h**
Fixes #214 and #233

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddConcertContactCommandParser.java [hunk 1]
```diff
@@ -16,32 +18,35 @@ public class AddConcertContactCommandParser implements Parser<AddConcertContactC
...
+        ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_PERSON,
+                PREFIX_CONCERT);
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_CONCERT);
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_PERSON);
 
-        Index indexP;
-        Index indexC;
         try {
-            //indexP = ParserUtil.parseIndex(argMultimap.getPreamble());
+            // indexP = ParserUtil.parseIndex(argMultimap.getPreamble());
```
Comment (bbbbcccd) [inline src/main/java/seedu/address/logic/parser/AddConcertContactCommandParser.java]: Remove comment

**Review by bbbbcccd — CHANGES_REQUESTED** [review]
lgtm with minor change!

**Review by bbbbcccd — APPROVED** [review]
Lgtm!
